services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/HDD/Docker/Sonarr/Volumes/Data:/config
      - /mnt/HDD2/Media/TV:/tv
      - /mnt/HDD/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped