services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=5140
      - TORRENTING_PORT=56119
    volumes:
      - /mnt/HDD/Docker/QBittorrent/Volumes/AppData:/config
      - /mnt/HDD/Downloads/QBittorrent:/downloads #optional
    ports:
      - 5140:5140
      - 6881:6881
      - 6881:6881/udp
      - 56119:56119
      - 56119:56119/udp
    restart: unless-stopped