services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/HDD/Docker/Radarr/Volumes/Data:/config
      - /mnt/HDD/Media/Movies:/movies
      - /mnt/HDD/Downloads/QBittorrent:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped