services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/HDD/Docker/Nzbget/Volumes/Config:/config
      - /mnt/HDD/Downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped