version: "3"
services:
  slskd:
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    ports:
      - 5030:5030/tcp
      - 5031:5031/tcp
      - 50300:50300/tcp
    volumes:
      - /mnt/HDD/Docker/Slskd/Volumes/App:/app
      - /mnt/HDD/Downloads/Slskd/Complete:/downloads
      - /mnt/HDD/Downloads/Slskd/Incomplete:/incomplete
    user: 1000:1000
    image: slskd/slskd:latest