services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/HDD/Docker/Bazarr/Volumes/Config:/config
      - /mnt/HDD/Media/Movies:/movies
      - /mnt/HDD2/Media/TV:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
