services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/HDD/Docker/Lidarr/Volumes/Config:/config
      - /mnt/HDD/Media/Music:/music
      #- /mnt/HDD/Downloads/QBittorrent:/downloads
      - /mnt/HDD/Docker/Slskd/Volumes/App/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped